openapi: 3.0.0
info:
  title: My Blog API
  version: 1.0.0
  description: API for My Blog
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
    Post:
      type: object
      properties:
        id:
          type: integer
        slug:
          type: string
        title:
          type: string
        excerpt:
          type: string
        content:
          type: string
        published:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        image:
          type: string
        author:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
        tags:
          type: array
          items:
            type: string
paths:
  /api/auth/login:
    post:
      summary: Login user
      tags: [Auth]
      security: []
      description: Login user and return access token and refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/auth/register:
    post:
      summary: Register user
      tags: [Register]
      security: []
      description: Register user and return access token and refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/auth/refresh:
    post:
      summary: Refresh access token
      tags: [Auth]
      security: []
      description: Use refresh token to get new access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: New access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  newRefreshToken:
                    type: string

  /api/auth/me:
    get:
      summary: Get current logged-in user
      tags: [Auth]
      description: Return current user info using access token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

  /api/users:
    get:
      summary: Get all users
      tags: [User Management]
      description: Get a paginated list of all users (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: List of users with pagination info
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
                        role:
                          type: string
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      pages:
                        type: integer
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not an admin
    
    post:
      summary: Create new user
      tags: [User Management]
      description: Create a new user (Admin only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [USER, ADMIN]
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  role:
                    type: string
        '400':
          description: Bad request - Missing required fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not an admin
        '409':
          description: Conflict - Email already exists
  
  /api/users/{id}:
    get:
      summary: Get user by ID
      tags: [User Management]
      description: Get user details by ID (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: User ID
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  role:
                    type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not an admin
        '404':
          description: User not found
    
    put:
      summary: Update user
      tags: [User Management]
      description: Update user details (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [USER, ADMIN]
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  role:
                    type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not an admin
        '404':
          description: User not found
        '409':
          description: Conflict - Email already exists
    
    delete:
      summary: Delete user
      tags: [User Management]
      description: Delete a user (Admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: User ID
      responses:
        '204':
          description: User deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not an admin
        '404':
          description: User not found
  /api/posts:
    get:
      summary: Get all posts
      tags: [Posts]
      description: Get a paginated list of all posts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items per page
        - in: query
          name: published
          schema:
            type: boolean
            default: true
          description: Filter by published status (admin only)
      responses:
        '200':
          description: List of posts with pagination info
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      pages:
                        type: integer
    
    post:
      summary: Create new post
      tags: [Posts]
      description: Create a new blog post
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                excerpt:
                  type: string
                content:
                  type: string
                image:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                published:
                  type: boolean
                  default: false
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Bad request - Missing required fields
        '401':
          description: Unauthorized

  /api/posts/{slug}:
    get:
      summary: Get post by slug
      tags: [Posts]
      description: Get post details by slug
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
          description: Post slug
      responses:
        '200':
          description: Post details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
    
    put:
      summary: Update post
      tags: [Posts]
      description: Update post details (only author or admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
          description: Post slug
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                excerpt:
                  type: string
                content:
                  type: string
                image:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                published:
                  type: boolean
      responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not the author or admin
        '404':
          description: Post not found
    
    delete:
      summary: Delete post
      tags: [Posts]
      description: Delete a post (only author or admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
          description: Post slug
      responses:
        '204':
          description: Post deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not the author or admin
        '404':
          description: Post not found

  /api/posts/tag/{tag}:
    get:
      summary: Get posts by tag
      tags: [Posts]
      description: Get posts filtered by tag
      parameters:
        - in: path
          name: tag
          required: true
          schema:
            type: string
          description: Tag name
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: List of posts with pagination info
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      pages:
                        type: integer

  /api/posts/tags:
    get:
      summary: Get all tags
      tags: [Posts]
      description: Get all available tags with post counts
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    postCount:
                      type: integer
