openapi: 3.0.0
info:
  title: My Blog API
  version: 1.0.0
  description: API for My Blog
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
        role:
          type: string
paths:
  /api/auth/login:
    post:
      summary: Login user
      tags: [Auth]
      security: []
      description: Login user and return access token and refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/auth/register:
    post:
      summary: Register user
      tags: [Register]
      security: []
      description: Register user and return access token and refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/auth/refresh:
    post:
      summary: Refresh access token
      tags: [Auth]
      security: []
      description: Use refresh token to get new access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: New access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /api/auth/me:
    get:
      summary: Get current logged-in user
      tags: [Auth]
      description: Return current user info using access token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
